export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    pin_hash TEXT NULL,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending'
  )`,
  `CREATE TABLE IF NOT EXISTS customers (
    id TEXT PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT NULL,
    notes TEXT NULL,
    firebase_uid TEXT NULL,
    referral_code TEXT NULL,
    external_source TEXT NULL,
    external_id TEXT NULL,
    is_imported INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending'
  )`,
  `CREATE TABLE IF NOT EXISTS vehicles (
    id TEXT PRIMARY KEY,
    customer_id TEXT NOT NULL,
    vin TEXT NULL,
    plate TEXT NULL,
    plate_state TEXT NULL,
    year INTEGER NULL,
    make TEXT NULL,
    model TEXT NULL,
    mileage INTEGER NULL,
    oil_type TEXT NULL,
    notes TEXT NULL,
    sub_model TEXT NULL,
    external_source TEXT NULL,
    external_id TEXT NULL,
    is_imported INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending',
    FOREIGN KEY (customer_id) REFERENCES customers(id)
  )`,
  `CREATE TABLE IF NOT EXISTS tickets (
    id TEXT PRIMARY KEY,
    customer_id TEXT NULL,
    vehicle_id TEXT NULL,
    status TEXT NOT NULL,
    subtotal REAL NOT NULL DEFAULT 0,
    discount_total REAL NOT NULL DEFAULT 0,
    tax_total REAL NOT NULL DEFAULT 0,
    fee_total REAL NOT NULL DEFAULT 0,
    total REAL NOT NULL DEFAULT 0,
    payment_status TEXT NOT NULL DEFAULT 'unpaid',
    notes TEXT NULL,
    customer_concern TEXT NULL,
    technician_notes TEXT NULL,
    internal_notes TEXT NULL,
    bay TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    completed_at TEXT NULL,
    external_source TEXT NULL,
    external_id TEXT NULL,
    is_imported INTEGER NOT NULL DEFAULT 0,
    original_import_json TEXT NULL,
    imported_at TEXT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending',
    FOREIGN KEY (customer_id) REFERENCES customers(id),
    FOREIGN KEY (vehicle_id) REFERENCES vehicles(id)
  )`,
  `CREATE TABLE IF NOT EXISTS ticket_items (
    id TEXT PRIMARY KEY,
    ticket_id TEXT NOT NULL,
    service_id TEXT NULL,
    item_type TEXT NULL,
    package_id TEXT NULL,
    inventory_item_id TEXT NULL,
    name TEXT NOT NULL,
    quantity REAL NOT NULL DEFAULT 1,
    unit_price REAL NOT NULL DEFAULT 0,
    line_total REAL NOT NULL DEFAULT 0,
    taxable INTEGER NOT NULL DEFAULT 1,
    external_source TEXT NULL,
    external_id TEXT NULL,
    is_imported INTEGER NOT NULL DEFAULT 0,
    original_import_json TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending',
    FOREIGN KEY (ticket_id) REFERENCES tickets(id),
    FOREIGN KEY (service_id) REFERENCES services(id)
  )`,
  `CREATE TABLE IF NOT EXISTS services (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT NULL,
    base_price REAL NOT NULL DEFAULT 0,
    taxable INTEGER NOT NULL DEFAULT 1,
    active INTEGER NOT NULL DEFAULT 1,
    is_oil_change INTEGER NOT NULL DEFAULT 0,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending'
  )`,
  `CREATE TABLE IF NOT EXISTS inventory_items (
    id TEXT PRIMARY KEY,
    sku TEXT NULL,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    vendor TEXT NULL,
    cost REAL NOT NULL DEFAULT 0,
    retail_price REAL NOT NULL DEFAULT 0,
    quantity_on_hand REAL NOT NULL DEFAULT 0,
    reorder_point REAL NOT NULL DEFAULT 0,
    barcode TEXT NULL,
    active INTEGER NOT NULL DEFAULT 1,
    notes TEXT NULL,
    external_source TEXT NULL,
    external_id TEXT NULL,
    is_imported INTEGER NOT NULL DEFAULT 0,
    product_id TEXT NULL,
    product_type TEXT NULL,
    inventory_type TEXT NULL,
    measurement TEXT NULL,
    viscosity TEXT NULL,
    oil_formulation TEXT NULL,
    quantity_sold_last_30_days REAL NULL,
    replacement_cost REAL NULL,
    avg_cost REAL NULL,
    min_quantity REAL NULL,
    max_quantity REAL NULL,
    sequence_id TEXT NULL,
    original_import_json TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending'
  )`,
  `CREATE TABLE IF NOT EXISTS payments (
    id TEXT PRIMARY KEY,
    ticket_id TEXT NOT NULL,
    method TEXT NOT NULL,
    amount REAL NOT NULL DEFAULT 0,
    status TEXT NOT NULL,
    reference TEXT NULL,
    paid_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    external_source TEXT NULL,
    external_id TEXT NULL,
    is_imported INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending',
    FOREIGN KEY (ticket_id) REFERENCES tickets(id)
  )`,
  `CREATE TABLE IF NOT EXISTS coupons (
    id TEXT PRIMARY KEY,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    discount_type TEXT NOT NULL,
    discount_value REAL NOT NULL DEFAULT 0,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending'
  )`,
  `CREATE TABLE IF NOT EXISTS referrals (
    id TEXT PRIMARY KEY,
    referrer_customer_id TEXT NOT NULL,
    referred_customer_id TEXT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending'
  )`,
  `CREATE TABLE IF NOT EXISTS sync_queue (
    id TEXT PRIMARY KEY,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    action TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    status TEXT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS import_batches (
    id TEXT PRIMARY KEY,
    source TEXT NOT NULL,
    file_name TEXT NOT NULL,
    import_type TEXT NOT NULL,
    status TEXT NOT NULL,
    rows_total INTEGER NOT NULL DEFAULT 0,
    rows_imported INTEGER NOT NULL DEFAULT 0,
    rows_skipped INTEGER NOT NULL DEFAULT 0,
    rows_failed INTEGER NOT NULL DEFAULT 0,
    summary_json TEXT NULL,
    started_at TEXT NOT NULL,
    completed_at TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS import_errors (
    id TEXT PRIMARY KEY,
    batch_id TEXT NOT NULL,
    row_number INTEGER NULL,
    message TEXT NOT NULL,
    row_json TEXT NULL,
    created_at TEXT NOT NULL,
    FOREIGN KEY (batch_id) REFERENCES import_batches(id)
  )`,
  `CREATE TABLE IF NOT EXISTS app_settings (
    id TEXT PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,
    value TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS service_history (
    id TEXT PRIMARY KEY,
    ticket_id TEXT NOT NULL,
    customer_id TEXT NOT NULL,
    vehicle_id TEXT NOT NULL,
    service_date TEXT NOT NULL,
    mileage INTEGER NOT NULL,
    oil_type TEXT NULL,
    services_json TEXT NOT NULL,
    notes TEXT NULL,
    external_source TEXT NULL,
    external_id TEXT NULL,
    is_imported INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending',
    FOREIGN KEY (ticket_id) REFERENCES tickets(id),
    FOREIGN KEY (customer_id) REFERENCES customers(id),
    FOREIGN KEY (vehicle_id) REFERENCES vehicles(id)
  )`,
  `CREATE TABLE IF NOT EXISTS service_packages (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NULL,
    category TEXT NOT NULL,
    base_price REAL NOT NULL,
    oil_brand TEXT NULL,
    oil_type TEXT NULL,
    included_quarts REAL NOT NULL DEFAULT 5,
    extra_quart_price REAL NOT NULL DEFAULT 0,
    included_filter_type TEXT NOT NULL DEFAULT 'standard',
    cartridge_filter_extra_fee REAL NOT NULL DEFAULT 0,
    max_included_filter_cost REAL NULL,
    taxable INTEGER NOT NULL DEFAULT 1,
    active INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending'
  )`,
  `CREATE TABLE IF NOT EXISTS service_catalog_items (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT NULL,
    sku TEXT NULL,
    base_price REAL NOT NULL,
    cost REAL NULL,
    taxable INTEGER NOT NULL DEFAULT 1,
    active INTEGER NOT NULL DEFAULT 1,
    is_oil_change INTEGER NOT NULL DEFAULT 0,
    is_fee INTEGER NOT NULL DEFAULT 0,
    is_discount INTEGER NOT NULL DEFAULT 0,
    inventory_item_id TEXT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending'
  )`,
  `CREATE TABLE IF NOT EXISTS package_addons (
    id TEXT PRIMARY KEY,
    package_id TEXT NOT NULL,
    catalog_item_id TEXT NOT NULL,
    included INTEGER NOT NULL DEFAULT 0,
    default_selected INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending'
  )`,
  `CREATE TABLE IF NOT EXISTS ticket_package_details (
    id TEXT PRIMARY KEY,
    ticket_id TEXT NOT NULL,
    package_id TEXT NOT NULL,
    package_name TEXT NOT NULL,
    oil_brand TEXT NULL,
    oil_type TEXT NULL,
    included_quarts REAL NOT NULL,
    actual_quarts REAL NOT NULL,
    extra_quarts REAL NOT NULL,
    extra_quart_price REAL NOT NULL,
    extra_quart_total REAL NOT NULL,
    filter_type TEXT NOT NULL,
    cartridge_filter_extra_fee REAL NOT NULL,
    package_base_price REAL NOT NULL,
    package_total REAL NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending'
  )`,
  "CREATE INDEX IF NOT EXISTS idx_customers_name ON customers(last_name, first_name)",
  "CREATE INDEX IF NOT EXISTS idx_customers_first_name ON customers(first_name)",
  "CREATE INDEX IF NOT EXISTS idx_customers_last_name ON customers(last_name)",
  "CREATE INDEX IF NOT EXISTS idx_customers_phone ON customers(phone)",
  "CREATE INDEX IF NOT EXISTS idx_customers_email ON customers(email)",
  "CREATE INDEX IF NOT EXISTS idx_vehicles_customer_id ON vehicles(customer_id)",
  "CREATE INDEX IF NOT EXISTS idx_vehicles_vin ON vehicles(vin)",
  "CREATE INDEX IF NOT EXISTS idx_vehicles_plate ON vehicles(plate, plate_state)",
  "CREATE INDEX IF NOT EXISTS idx_vehicles_year_make_model ON vehicles(year, make, model)",
  "CREATE INDEX IF NOT EXISTS idx_tickets_status ON tickets(status)",
  "CREATE INDEX IF NOT EXISTS idx_tickets_external_id ON tickets(external_id)",
  "CREATE INDEX IF NOT EXISTS idx_tickets_bay ON tickets(bay)",
  "CREATE INDEX IF NOT EXISTS idx_service_history_vehicle ON service_history(vehicle_id)",
  "CREATE INDEX IF NOT EXISTS idx_service_history_customer ON service_history(customer_id)",
  "CREATE INDEX IF NOT EXISTS idx_service_packages_active ON service_packages(active, sort_order)",
  "CREATE INDEX IF NOT EXISTS idx_catalog_items_active ON service_catalog_items(active, category)",
  "CREATE INDEX IF NOT EXISTS idx_ticket_package_details_ticket ON ticket_package_details(ticket_id)",
  "CREATE INDEX IF NOT EXISTS idx_tickets_external ON tickets(external_source, external_id)",
  "CREATE INDEX IF NOT EXISTS idx_customers_external ON customers(external_source, external_id)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_external ON inventory_items(external_source, external_id)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_sku ON inventory_items(sku)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_product_id ON inventory_items(product_id)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_barcode ON inventory_items(barcode)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_name ON inventory_items(name)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_product_type ON inventory_items(product_type)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_vendor ON inventory_items(vendor)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_viscosity ON inventory_items(viscosity)",
  "CREATE INDEX IF NOT EXISTS idx_import_errors_batch ON import_errors(batch_id)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_low_stock ON inventory_items(quantity_on_hand, reorder_point)",
  "CREATE INDEX IF NOT EXISTS idx_sync_queue_status ON sync_queue(status)"
];

export interface ColumnMigration {
  tableName: string;
  columnName: string;
  columnDefinition: string;
}

export const columnMigrations: ColumnMigration[] = [
  { tableName: "tickets", columnName: "bay", columnDefinition: "TEXT NULL" },
  { tableName: "tickets", columnName: "customer_concern", columnDefinition: "TEXT NULL" },
  { tableName: "tickets", columnName: "technician_notes", columnDefinition: "TEXT NULL" },
  { tableName: "tickets", columnName: "internal_notes", columnDefinition: "TEXT NULL" },
  { tableName: "tickets", columnName: "completed_at", columnDefinition: "TEXT NULL" },
  { tableName: "tickets", columnName: "payment_status", columnDefinition: "TEXT NOT NULL DEFAULT 'unpaid'" },
  { tableName: "tickets", columnName: "external_source", columnDefinition: "TEXT NULL" },
  { tableName: "tickets", columnName: "external_id", columnDefinition: "TEXT NULL" },
  { tableName: "tickets", columnName: "is_imported", columnDefinition: "INTEGER NOT NULL DEFAULT 0" },
  { tableName: "tickets", columnName: "original_import_json", columnDefinition: "TEXT NULL" },
  { tableName: "tickets", columnName: "imported_at", columnDefinition: "TEXT NULL" },

  { tableName: "customers", columnName: "external_source", columnDefinition: "TEXT NULL" },
  { tableName: "customers", columnName: "external_id", columnDefinition: "TEXT NULL" },
  { tableName: "customers", columnName: "is_imported", columnDefinition: "INTEGER NOT NULL DEFAULT 0" },

  { tableName: "vehicles", columnName: "external_source", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "external_id", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "is_imported", columnDefinition: "INTEGER NOT NULL DEFAULT 0" },
  { tableName: "vehicles", columnName: "sub_model", columnDefinition: "TEXT NULL" },

  { tableName: "ticket_items", columnName: "item_type", columnDefinition: "TEXT NULL" },
  { tableName: "ticket_items", columnName: "package_id", columnDefinition: "TEXT NULL" },
  { tableName: "ticket_items", columnName: "inventory_item_id", columnDefinition: "TEXT NULL" },
  { tableName: "ticket_items", columnName: "external_source", columnDefinition: "TEXT NULL" },
  { tableName: "ticket_items", columnName: "external_id", columnDefinition: "TEXT NULL" },
  { tableName: "ticket_items", columnName: "is_imported", columnDefinition: "INTEGER NOT NULL DEFAULT 0" },
  { tableName: "ticket_items", columnName: "original_import_json", columnDefinition: "TEXT NULL" },

  { tableName: "payments", columnName: "paid_at", columnDefinition: "TEXT NULL" },
  { tableName: "payments", columnName: "external_source", columnDefinition: "TEXT NULL" },
  { tableName: "payments", columnName: "external_id", columnDefinition: "TEXT NULL" },
  { tableName: "payments", columnName: "is_imported", columnDefinition: "INTEGER NOT NULL DEFAULT 0" },

  { tableName: "service_history", columnName: "external_source", columnDefinition: "TEXT NULL" },
  { tableName: "service_history", columnName: "external_id", columnDefinition: "TEXT NULL" },
  { tableName: "service_history", columnName: "is_imported", columnDefinition: "INTEGER NOT NULL DEFAULT 0" },

  { tableName: "inventory_items", columnName: "external_source", columnDefinition: "TEXT NULL" },
  { tableName: "inventory_items", columnName: "external_id", columnDefinition: "TEXT NULL" },
  { tableName: "inventory_items", columnName: "is_imported", columnDefinition: "INTEGER NOT NULL DEFAULT 0" },
  { tableName: "inventory_items", columnName: "product_id", columnDefinition: "TEXT NULL" },
  { tableName: "inventory_items", columnName: "product_type", columnDefinition: "TEXT NULL" },
  { tableName: "inventory_items", columnName: "inventory_type", columnDefinition: "TEXT NULL" },
  { tableName: "inventory_items", columnName: "measurement", columnDefinition: "TEXT NULL" },
  { tableName: "inventory_items", columnName: "viscosity", columnDefinition: "TEXT NULL" },
  { tableName: "inventory_items", columnName: "oil_formulation", columnDefinition: "TEXT NULL" },
  { tableName: "inventory_items", columnName: "quantity_sold_last_30_days", columnDefinition: "REAL NULL" },
  { tableName: "inventory_items", columnName: "replacement_cost", columnDefinition: "REAL NULL" },
  { tableName: "inventory_items", columnName: "avg_cost", columnDefinition: "REAL NULL" },
  { tableName: "inventory_items", columnName: "min_quantity", columnDefinition: "REAL NULL" },
  { tableName: "inventory_items", columnName: "max_quantity", columnDefinition: "REAL NULL" },
  { tableName: "inventory_items", columnName: "sequence_id", columnDefinition: "TEXT NULL" },
  { tableName: "inventory_items", columnName: "original_import_json", columnDefinition: "TEXT NULL" }
];

export const seedServices = [
  ["synthetic-blend-oil-change", "Synthetic Blend Oil Change", "Oil Change", 64.99, 1, 1],
  ["full-synthetic-oil-change", "Full Synthetic Oil Change", "Oil Change", 84.99, 1, 1],
  ["mobil-1-full-synthetic-oil-change", "Mobil 1 Full Synthetic Oil Change", "Oil Change", 99.99, 1, 1],
  ["diesel-oil-change", "Diesel Oil Change", "Oil Change", 119.99, 1, 1],
  ["air-filter", "Air Filter", "Filters", 24.99, 1, 0],
  ["cabin-air-filter", "Cabin Air Filter", "Filters", 34.99, 1, 0],
  ["wiper-blades", "Wiper Blades", "Wipers", 19.99, 1, 0],
  ["tire-rotation", "Tire Rotation", "Tires", 24.99, 1, 0],
  ["shop-supplies", "Shop Supplies", "Fees", 3.99, 1, 0],
  ["disposal-fee", "Disposal Fee", "Fees", 2.99, 0, 0]
] as const;

export const seedInventoryItems = [
  ["OF4622", "OF4622", "Engine Oil Filter", "Filters", "Service Champ", 3.75, 9.99, 18, 6, "Oil filter"],
  ["OF241", "OF241", "Engine Oil Filter", "Filters", "Service Champ", 3.5, 9.99, 14, 6, "Oil filter"],
  ["DURAMAX-BLND5W20", "DURAMAX-BLND5W20", "Engine Oil", "Oil", "Duramax", 18.25, 34.99, 42, 12, "Synthetic blend 5W-20"],
  ["AF1388", "AF1388", "Air Filter", "Filters", null, 8.25, 24.99, 9, 4, "Air filter"],
  ["CF10285", "CF10285", "Cabin Air Filter", "Filters", null, 10.5, 34.99, 6, 3, "Cabin air filter"]
] as const;

export const seedServicePackages = [
  ["synthetic-blend-oil-change", "Synthetic Blend Oil Change", "Oil Change", 64.99, "Duramax", "Synthetic Blend", 6, 7.99, "standard", 10.0, 1],
  ["full-synthetic-oil-change", "Full Synthetic Oil Change", "Oil Change", 79.99, "Duramax", "Full Synthetic", 6, 9.99, "standard", 10.0, 2],
  ["mobil-1-full-synthetic-oil-change", "Mobil 1 Full Synthetic Oil Change", "Oil Change", 94.99, "Mobil 1", "Full Synthetic", 5, 11.99, "standard", 10.0, 3],
  ["diesel-oil-change", "Diesel Oil Change", "Oil Change", 119.99, "Duramax", "Diesel", 10, 9.99, "standard", 15.0, 4]
] as const;

export const seedCatalogItems = [
  ["air-filter", "Air Filter", "Filters", 24.99, 0, 0, 1],
  ["premium-air-filter", "Premium Air Filter", "Filters", 34.99, 0, 0, 2],
  ["cabin-air-filter", "Cabin Air Filter", "Filters", 34.99, 0, 0, 3],
  ["premium-cabin-air-filter", "Premium Cabin Air Filter", "Filters", 44.99, 0, 0, 4],
  ["wiper-blade", "Wiper Blade", "Wipers", 19.99, 0, 0, 10],
  ["premium-wiper-blade", "Premium Wiper Blade", "Wipers", 29.99, 0, 0, 11],
  ["washer-fluid-top-off", "Washer Fluid Top-Off", "Fluids", 0.0, 0, 0, 20],
  ["coolant-top-off", "Coolant Top-Off", "Fluids", 4.99, 0, 0, 21],
  ["power-steering-fluid-top-off", "Power Steering Fluid Top-Off", "Fluids", 4.99, 0, 0, 22],
  ["brake-fluid-top-off", "Brake Fluid Top-Off", "Fluids", 4.99, 0, 0, 23],
  ["shop-supplies", "Shop Supplies", "Fees", 3.99, 1, 0, 30],
  ["disposal-fee", "Disposal Fee", "Fees", 2.99, 1, 0, 31],
  ["cartridge-filter-fee", "Cartridge Filter Fee", "Fees", 10.0, 1, 0, 32],
  ["skid-plate-fee", "Skid Plate Fee", "Fees", 5.0, 1, 0, 33],
  ["manual-discount", "Manual Discount", "Discounts", 0.0, 0, 1, 40],
  ["coupon-discount", "Coupon Discount", "Discounts", 0.0, 0, 1, 41],
  ["free-oil-change-reward", "Free Oil Change Reward", "Discounts", 0.0, 0, 1, 42],
  ["tire-rotation", "Tire Rotation", "Tires", 24.99, 0, 0, 50],
  ["battery-test", "Battery Test", "Battery", 0.0, 0, 0, 60],
  ["battery-replacement-labor", "Battery Replacement Labor", "Battery", 24.99, 0, 0, 61],
  ["light-bulb-replacement-labor", "Light Bulb Replacement Labor", "Lights", 14.99, 0, 0, 70]
] as const;
