export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    pin_hash TEXT NULL,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending'
  )`,
  `CREATE TABLE IF NOT EXISTS employees (
    id TEXT PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    display_name TEXT NOT NULL,
    email TEXT NULL,
    phone TEXT NULL,
    role TEXT NOT NULL,
    pin_hash TEXT NULL,
    active INTEGER NOT NULL DEFAULT 1,
    hourly_rate REAL NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending'
  )`,
  `CREATE TABLE IF NOT EXISTS customers (
    id TEXT PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT NULL,
    notes TEXT NULL,
    firebase_uid TEXT NULL,
    app_email TEXT NULL,
    app_phone TEXT NULL,
    app_link_status TEXT NULL,
    app_linked_at TEXT NULL,
    referral_code TEXT NULL,
    external_source TEXT NULL,
    external_id TEXT NULL,
    is_imported INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending'
  )`,
  `CREATE TABLE IF NOT EXISTS vehicles (
    id TEXT PRIMARY KEY,
    customer_id TEXT NOT NULL,
    vin TEXT NULL,
    plate TEXT NULL,
    plate_state TEXT NULL,
    year INTEGER NULL,
    make TEXT NULL,
    model TEXT NULL,
    trim TEXT NULL,
    series TEXT NULL,
    body_class TEXT NULL,
    vehicle_type TEXT NULL,
    doors INTEGER NULL,
    drive_type TEXT NULL,
    fuel_type TEXT NULL,
    engine_cylinders INTEGER NULL,
    engine_displacement_l REAL NULL,
    engine_displacement_cc REAL NULL,
    engine_model TEXT NULL,
    engine_configuration TEXT NULL,
    manufacturer TEXT NULL,
    plant_country TEXT NULL,
    plant_state TEXT NULL,
    transmission_style TEXT NULL,
    gvwr TEXT NULL,
    brake_system_type TEXT NULL,
    mileage INTEGER NULL,
    oil_type TEXT NULL,
    oil_capacity REAL NULL,
    oil_filter_sku TEXT NULL,
    oil_filter_inventory_item_id TEXT NULL,
    air_filter_sku TEXT NULL,
    cabin_filter_sku TEXT NULL,
    vehicle_info_notes TEXT NULL,
    vehicle_info_source_url TEXT NULL,
    vehicle_info_source_title TEXT NULL,
    vehicle_info_verified_at TEXT NULL,
    vehicle_info_verified_by_employee_id TEXT NULL,
    last_oil_change_date TEXT NULL,
    last_oil_change_mileage INTEGER NULL,
    vin_decoded_at TEXT NULL,
    vin_decode_source TEXT NULL,
    vin_decode_confidence TEXT NULL,
    vin_decode_raw_json TEXT NULL,
    notes TEXT NULL,
    sub_model TEXT NULL,
    external_source TEXT NULL,
    external_id TEXT NULL,
    is_imported INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending',
    FOREIGN KEY (customer_id) REFERENCES customers(id)
  )`,
  `CREATE TABLE IF NOT EXISTS tickets (
    id TEXT PRIMARY KEY,
    invoice_number TEXT NULL,
    customer_id TEXT NULL,
    vehicle_id TEXT NULL,
    status TEXT NOT NULL,
    subtotal REAL NOT NULL DEFAULT 0,
    discount_total REAL NOT NULL DEFAULT 0,
    applied_coupon_ids TEXT NULL,
    free_oil_change_redeemed INTEGER NOT NULL DEFAULT 0,
    tax_total REAL NOT NULL DEFAULT 0,
    fee_total REAL NOT NULL DEFAULT 0,
    total REAL NOT NULL DEFAULT 0,
    payment_status TEXT NOT NULL DEFAULT 'unpaid',
    notes TEXT NULL,
    customer_concern TEXT NULL,
    technician_notes TEXT NULL,
    internal_notes TEXT NULL,
    bay TEXT NULL,
    check_in_id TEXT NULL,
    started_at TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    completed_at TEXT NULL,
    external_source TEXT NULL,
    external_id TEXT NULL,
    is_imported INTEGER NOT NULL DEFAULT 0,
    original_import_json TEXT NULL,
    imported_at TEXT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending',
    FOREIGN KEY (customer_id) REFERENCES customers(id),
    FOREIGN KEY (vehicle_id) REFERENCES vehicles(id)
  )`,
  `CREATE TABLE IF NOT EXISTS ticket_items (
    id TEXT PRIMARY KEY,
    ticket_id TEXT NOT NULL,
    service_id TEXT NULL,
    item_type TEXT NULL,
    package_id TEXT NULL,
    inventory_item_id TEXT NULL,
    name TEXT NOT NULL,
    quantity REAL NOT NULL DEFAULT 1,
    unit_price REAL NOT NULL DEFAULT 0,
    line_total REAL NOT NULL DEFAULT 0,
    taxable INTEGER NOT NULL DEFAULT 1,
    external_source TEXT NULL,
    external_id TEXT NULL,
    is_imported INTEGER NOT NULL DEFAULT 0,
    original_import_json TEXT NULL,
    inventory_decremented INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending',
    FOREIGN KEY (ticket_id) REFERENCES tickets(id),
    FOREIGN KEY (service_id) REFERENCES services(id)
  )`,
  `CREATE TABLE IF NOT EXISTS services (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT NULL,
    base_price REAL NOT NULL DEFAULT 0,
    taxable INTEGER NOT NULL DEFAULT 1,
    active INTEGER NOT NULL DEFAULT 1,
    is_oil_change INTEGER NOT NULL DEFAULT 0,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending'
  )`,
  `CREATE TABLE IF NOT EXISTS inventory_items (
    id TEXT PRIMARY KEY,
    sku TEXT NULL,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    vendor TEXT NULL,
    brand TEXT NULL,
    supplier TEXT NULL,
    cost REAL NOT NULL DEFAULT 0,
    retail_price REAL NOT NULL DEFAULT 0,
    quantity_on_hand REAL NOT NULL DEFAULT 0,
    reorder_point REAL NOT NULL DEFAULT 0,
    barcode TEXT NULL,
    tax_exempt INTEGER NOT NULL DEFAULT 0,
    trackable INTEGER NOT NULL DEFAULT 1,
    sellable INTEGER NOT NULL DEFAULT 1,
    replenishable INTEGER NOT NULL DEFAULT 1,
    active INTEGER NOT NULL DEFAULT 1,
    notes TEXT NULL,
    external_source TEXT NULL,
    external_id TEXT NULL,
    is_imported INTEGER NOT NULL DEFAULT 0,
    product_id TEXT NULL,
    product_type TEXT NULL,
    inventory_type TEXT NULL,
    measurement TEXT NULL,
    viscosity TEXT NULL,
    oil_formulation TEXT NULL,
    quantity_sold_last_30_days REAL NULL,
    replacement_cost REAL NULL,
    avg_cost REAL NULL,
    min_quantity REAL NULL,
    max_quantity REAL NULL,
    sequence_id TEXT NULL,
    original_import_json TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending'
  )`,
  `CREATE TABLE IF NOT EXISTS inventory_movements (
    id TEXT PRIMARY KEY,
    inventory_item_id TEXT NOT NULL,
    movement_type TEXT NOT NULL,
    quantity_before REAL NOT NULL,
    quantity_change REAL NOT NULL,
    quantity_after REAL NOT NULL,
    reason TEXT NULL,
    notes TEXT NULL,
    created_at TEXT NOT NULL,
    created_by TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending',
    FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id)
  )`,
  `CREATE TABLE IF NOT EXISTS inventory_count_sheets (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    filter_type TEXT NULL,
    created_by_employee_id TEXT NULL,
    completed_by_employee_id TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    completed_at TEXT NULL,
    notes TEXT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS inventory_count_sheet_items (
    id TEXT PRIMARY KEY,
    count_sheet_id TEXT NOT NULL,
    inventory_item_id TEXT NOT NULL,
    expected_quantity REAL NOT NULL DEFAULT 0,
    counted_quantity REAL NULL,
    variance REAL NULL,
    adjustment_applied INTEGER NOT NULL DEFAULT 0,
    notes TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (count_sheet_id) REFERENCES inventory_count_sheets(id),
    FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id)
  )`,
  `CREATE TABLE IF NOT EXISTS suppliers (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    contact_name TEXT NULL,
    phone TEXT NULL,
    email TEXT NULL,
    website TEXT NULL,
    notes TEXT NULL,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS purchase_orders (
    id TEXT PRIMARY KEY,
    supplier_id TEXT NULL,
    supplier_name TEXT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    order_date TEXT NULL,
    expected_date TEXT NULL,
    received_date TEXT NULL,
    subtotal REAL NOT NULL DEFAULT 0,
    notes TEXT NULL,
    created_by_employee_id TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
  )`,
  `CREATE TABLE IF NOT EXISTS purchase_order_items (
    id TEXT PRIMARY KEY,
    purchase_order_id TEXT NOT NULL,
    inventory_item_id TEXT NOT NULL,
    product_id TEXT NULL,
    name TEXT NOT NULL,
    quantity_ordered REAL NOT NULL,
    quantity_received REAL NOT NULL DEFAULT 0,
    unit_cost REAL NOT NULL DEFAULT 0,
    line_total REAL NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id),
    FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id)
  )`,
  `CREATE TABLE IF NOT EXISTS payments (
    id TEXT PRIMARY KEY,
    ticket_id TEXT NOT NULL,
    method TEXT NOT NULL,
    payment_subtype TEXT NULL,
    amount REAL NOT NULL DEFAULT 0,
    status TEXT NOT NULL,
    reference TEXT NULL,
    memo TEXT NULL,
    paid_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    external_source TEXT NULL,
    external_id TEXT NULL,
    is_imported INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending',
    FOREIGN KEY (ticket_id) REFERENCES tickets(id)
  )`,
  `CREATE TABLE IF NOT EXISTS quotes (
    id TEXT PRIMARY KEY,
    quote_number TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'draft',
    customer_name TEXT NULL,
    customer_phone TEXT NULL,
    customer_email TEXT NULL,
    customer_id TEXT NULL,
    vehicle_id TEXT NULL,
    vehicle_year TEXT NULL,
    vehicle_make TEXT NULL,
    vehicle_model TEXT NULL,
    vehicle_vin TEXT NULL,
    vehicle_plate TEXT NULL,
    vehicle_plate_state TEXT NULL,
    vehicle_mileage REAL NULL,
    subtotal REAL NOT NULL DEFAULT 0,
    discount_total REAL NOT NULL DEFAULT 0,
    tax_total REAL NOT NULL DEFAULT 0,
    total REAL NOT NULL DEFAULT 0,
    notes TEXT NULL,
    converted_ticket_id TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    converted_at TEXT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending'
  )`,
  `CREATE TABLE IF NOT EXISTS quote_items (
    id TEXT PRIMARY KEY,
    quote_id TEXT NOT NULL,
    item_type TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT NULL,
    quantity REAL NOT NULL DEFAULT 1,
    unit_price REAL NOT NULL DEFAULT 0,
    line_total REAL NOT NULL DEFAULT 0,
    taxable INTEGER NOT NULL DEFAULT 1,
    inventory_item_id TEXT NULL,
    package_id TEXT NULL,
    metadata_json TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending',
    FOREIGN KEY (quote_id) REFERENCES quotes(id)
  )`,
  `CREATE TABLE IF NOT EXISTS coupons (
    id TEXT PRIMARY KEY,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    discount_type TEXT NOT NULL,
    discount_value REAL NOT NULL DEFAULT 0,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending'
  )`,
  `CREATE TABLE IF NOT EXISTS referrals (
    id TEXT PRIMARY KEY,
    referrer_customer_id TEXT NOT NULL,
    referred_customer_id TEXT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending'
  )`,
  `CREATE TABLE IF NOT EXISTS sync_queue (
    id TEXT PRIMARY KEY,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    action TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    status TEXT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS import_batches (
    id TEXT PRIMARY KEY,
    source TEXT NOT NULL,
    file_name TEXT NOT NULL,
    import_type TEXT NOT NULL,
    status TEXT NOT NULL,
    rows_total INTEGER NOT NULL DEFAULT 0,
    rows_imported INTEGER NOT NULL DEFAULT 0,
    rows_skipped INTEGER NOT NULL DEFAULT 0,
    rows_failed INTEGER NOT NULL DEFAULT 0,
    summary_json TEXT NULL,
    started_at TEXT NOT NULL,
    completed_at TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS import_errors (
    id TEXT PRIMARY KEY,
    batch_id TEXT NOT NULL,
    row_number INTEGER NULL,
    message TEXT NOT NULL,
    row_json TEXT NULL,
    created_at TEXT NOT NULL,
    FOREIGN KEY (batch_id) REFERENCES import_batches(id)
  )`,
  `CREATE TABLE IF NOT EXISTS app_settings (
    id TEXT PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,
    value TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS service_history (
    id TEXT PRIMARY KEY,
    ticket_id TEXT NOT NULL,
    customer_id TEXT NOT NULL,
    vehicle_id TEXT NOT NULL,
    service_date TEXT NOT NULL,
    mileage INTEGER NOT NULL,
    oil_type TEXT NULL,
    services_json TEXT NOT NULL,
    notes TEXT NULL,
    external_source TEXT NULL,
    external_id TEXT NULL,
    is_imported INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending',
    FOREIGN KEY (ticket_id) REFERENCES tickets(id),
    FOREIGN KEY (customer_id) REFERENCES customers(id),
    FOREIGN KEY (vehicle_id) REFERENCES vehicles(id)
  )`,
  `CREATE TABLE IF NOT EXISTS service_packages (
    id TEXT PRIMARY KEY,
    external_source TEXT NULL,
    external_id TEXT NULL,
    name TEXT NOT NULL,
    internal_name TEXT NULL,
    description TEXT NULL,
    category TEXT NOT NULL,
    base_price REAL NOT NULL,
    package_total REAL NULL,
    base_service_amount REAL NULL,
    disposal_fee_amount REAL NULL,
    disposal_fee_quantity REAL NULL,
    mileage_interval INTEGER NULL,
    time_interval_months INTEGER NULL,
    service_1_id TEXT NULL,
    service_1_name TEXT NULL,
    service_2_id TEXT NULL,
    service_2_name TEXT NULL,
    services_json TEXT NULL,
    package_group_name TEXT NULL,
    oil_brand TEXT NULL,
    oil_type TEXT NULL,
    included_quarts REAL NOT NULL DEFAULT 5,
    extra_quart_price REAL NOT NULL DEFAULT 0,
    included_filter_type TEXT NOT NULL DEFAULT 'standard',
    cartridge_filter_extra_fee REAL NOT NULL DEFAULT 0,
    max_included_filter_cost REAL NULL,
    taxable INTEGER NOT NULL DEFAULT 1,
    active INTEGER NOT NULL DEFAULT 1,
    visible_in_start_ticket INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending'
  )`,
  `CREATE TABLE IF NOT EXISTS service_catalog_items (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT NULL,
    sku TEXT NULL,
    base_price REAL NOT NULL,
    cost REAL NULL,
    taxable INTEGER NOT NULL DEFAULT 1,
    active INTEGER NOT NULL DEFAULT 1,
    is_oil_change INTEGER NOT NULL DEFAULT 0,
    is_fee INTEGER NOT NULL DEFAULT 0,
    is_discount INTEGER NOT NULL DEFAULT 0,
    inventory_item_id TEXT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending'
  )`,
  `CREATE TABLE IF NOT EXISTS package_addons (
    id TEXT PRIMARY KEY,
    package_id TEXT NOT NULL,
    catalog_item_id TEXT NOT NULL,
    included INTEGER NOT NULL DEFAULT 0,
    default_selected INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending'
  )`,
  `CREATE TABLE IF NOT EXISTS ticket_package_details (
    id TEXT PRIMARY KEY,
    ticket_id TEXT NOT NULL,
    package_id TEXT NOT NULL,
    package_name TEXT NOT NULL,
    oil_brand TEXT NULL,
    oil_type TEXT NULL,
    included_quarts REAL NOT NULL,
    actual_quarts REAL NOT NULL,
    extra_quarts REAL NOT NULL,
    extra_quart_price REAL NOT NULL,
    extra_quart_total REAL NOT NULL,
    filter_type TEXT NOT NULL,
    cartridge_filter_extra_fee REAL NOT NULL,
    oil_filter_inventory_item_id TEXT NULL,
    oil_filter_sku TEXT NULL,
    oil_filter_name TEXT NULL,
    oil_filter_source TEXT NULL,
    oil_inventory_item_id TEXT NULL,
    oil_sku TEXT NULL,
    oil_name TEXT NULL,
    oil_source TEXT NULL,
    package_base_price REAL NOT NULL,
    package_total REAL NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending'
  )`,
  `CREATE TABLE IF NOT EXISTS window_stickers (
    id TEXT PRIMARY KEY,
    ticket_id TEXT NOT NULL,
    customer_id TEXT NULL,
    vehicle_id TEXT NULL,
    sticker_type TEXT NOT NULL DEFAULT 'oil_change',
    status TEXT NOT NULL DEFAULT 'queued',
    print_data_json TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    printed_at TEXT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending',
    FOREIGN KEY (ticket_id) REFERENCES tickets(id),
    FOREIGN KEY (customer_id) REFERENCES customers(id),
    FOREIGN KEY (vehicle_id) REFERENCES vehicles(id)
  )`,
  `CREATE TABLE IF NOT EXISTS print_jobs (
    id TEXT PRIMARY KEY,
    ticket_id TEXT NULL,
    document_type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'created',
    print_mode TEXT NOT NULL,
    printer_model TEXT NULL,
    printer_language TEXT NULL,
    template_id TEXT NULL,
    payload_json TEXT NOT NULL,
    rendered_html TEXT NULL,
    raw_command TEXT NULL,
    error_message TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    printed_at TEXT NULL,
    created_by TEXT NULL,
    FOREIGN KEY (ticket_id) REFERENCES tickets(id)
  )`,
  `CREATE TABLE IF NOT EXISTS vin_decode_cache (
    id TEXT PRIMARY KEY,
    vin TEXT NOT NULL UNIQUE,
    provider TEXT NOT NULL,
    normalized_json TEXT NOT NULL,
    raw_json TEXT NULL,
    confidence TEXT NULL,
    decoded_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS fuel_economy_cache (
    id TEXT PRIMARY KEY,
    cache_key TEXT NOT NULL UNIQUE,
    provider TEXT NOT NULL,
    response_json TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    expires_at TEXT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS geocoding_cache (
    id TEXT PRIMARY KEY,
    cache_key TEXT NOT NULL UNIQUE,
    provider TEXT NOT NULL,
    response_json TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    expires_at TEXT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS vehicle_info_lookup_history (
    id TEXT PRIMARY KEY,
    vehicle_id TEXT NULL,
    vin TEXT NULL,
    year TEXT NULL,
    make TEXT NULL,
    model TEXT NULL,
    engine TEXT NULL,
    query TEXT NOT NULL,
    provider TEXT NOT NULL,
    source_url TEXT NULL,
    source_title TEXT NULL,
    suggested_json TEXT NULL,
    selected_json TEXT NULL,
    status TEXT NOT NULL DEFAULT 'reviewed',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    employee_id TEXT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS vehicle_info_search_cache (
    id TEXT PRIMARY KEY,
    query TEXT NOT NULL UNIQUE,
    provider TEXT NOT NULL,
    response_json TEXT NOT NULL,
    created_at TEXT NOT NULL,
    expires_at TEXT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS vehicle_catalog_cache (
    id TEXT PRIMARY KEY,
    provider TEXT NOT NULL,
    cache_type TEXT NOT NULL,
    cache_key TEXT NOT NULL UNIQUE,
    response_json TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    expires_at TEXT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS vehicle_catalog_options (
    id TEXT PRIMARY KEY,
    provider TEXT NOT NULL,
    provider_option_id TEXT NULL,
    year INTEGER NOT NULL,
    make TEXT NOT NULL,
    model TEXT NOT NULL,
    trim TEXT NULL,
    engine TEXT NULL,
    displacement TEXT NULL,
    cylinders TEXT NULL,
    transmission TEXT NULL,
    drive TEXT NULL,
    fuel_type TEXT NULL,
    body_class TEXT NULL,
    raw_json TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS loyalty_sync_queue (
    id TEXT PRIMARY KEY,
    event_type TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error TEXT NULL,
    dry_run_result_json TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    synced_at TEXT NULL,
    next_retry_at TEXT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS vehicle_punch_cards (
    id TEXT PRIMARY KEY,
    customer_id TEXT NOT NULL,
    vehicle_id TEXT NOT NULL,
    punch_count INTEGER NOT NULL DEFAULT 0,
    free_rewards_available INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending'
  )`,
  `CREATE TABLE IF NOT EXISTS vehicle_punch_events (
    id TEXT PRIMARY KEY,
    punch_card_id TEXT NOT NULL,
    ticket_id TEXT NULL,
    event_type TEXT NOT NULL,
    punch_delta INTEGER NOT NULL,
    reward_delta INTEGER NOT NULL DEFAULT 0,
    note TEXT NULL,
    created_at TEXT NOT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending'
  )`,
  `CREATE TABLE IF NOT EXISTS referral_rewards (
    id TEXT PRIMARY KEY,
    referrer_customer_id TEXT NOT NULL,
    referred_customer_id TEXT NOT NULL,
    referred_ticket_id TEXT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    reward_amount REAL NOT NULL DEFAULT 10,
    completed_at TEXT NULL,
    rewarded_at TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending'
  )`,
  `CREATE TABLE IF NOT EXISTS customer_coupons (
    id TEXT PRIMARY KEY,
    customer_id TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NULL,
    discount_type TEXT NOT NULL,
    discount_amount REAL NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'active',
    source TEXT NULL,
    source_id TEXT NULL,
    issued_at TEXT NOT NULL,
    expires_at TEXT NULL,
    redeemed_at TEXT NULL,
    redeemed_ticket_id TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending'
  )`,
  `CREATE TABLE IF NOT EXISTS ticket_coupon_applications (
    id TEXT PRIMARY KEY,
    ticket_id TEXT NOT NULL,
    coupon_id TEXT NOT NULL,
    customer_id TEXT NOT NULL,
    discount_type TEXT NOT NULL,
    discount_amount REAL NOT NULL,
    calculated_discount REAL NOT NULL,
    status TEXT NOT NULL DEFAULT 'applied',
    applied_at TEXT NOT NULL,
    redeemed_at TEXT NULL,
    removed_at TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending'
  )`,
  `CREATE TABLE IF NOT EXISTS audit_log (
    id TEXT PRIMARY KEY,
    actor_employee_id TEXT NULL,
    actor_name TEXT NULL,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT NULL,
    summary TEXT NOT NULL,
    before_json TEXT NULL,
    after_json TEXT NULL,
    metadata_json TEXT NULL,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS daily_closeouts (
    id TEXT PRIMARY KEY,
    business_date TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'open',
    opened_at TEXT NOT NULL,
    closed_at TEXT NULL,
    closed_by_employee_id TEXT NULL,
    gross_sales REAL NOT NULL DEFAULT 0,
    net_sales REAL NOT NULL DEFAULT 0,
    tax_collected REAL NOT NULL DEFAULT 0,
    discount_total REAL NOT NULL DEFAULT 0,
    cash_total REAL NOT NULL DEFAULT 0,
    card_total REAL NOT NULL DEFAULT 0,
    check_total REAL NOT NULL DEFAULT 0,
    other_total REAL NOT NULL DEFAULT 0,
    cash_counted REAL NULL,
    cash_over_short REAL NULL,
    completed_ticket_count INTEGER NOT NULL DEFAULT 0,
    vehicle_count INTEGER NOT NULL DEFAULT 0,
    notes TEXT NULL,
    summary_json TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS employee_time_entries (
    id TEXT PRIMARY KEY,
    employee_id TEXT NOT NULL,
    entry_type TEXT NOT NULL,
    timestamp TEXT NOT NULL,
    note TEXT NULL,
    created_at TEXT NOT NULL,
    created_by_employee_id TEXT NULL,
    edited_at TEXT NULL,
    edited_by_employee_id TEXT NULL,
    deleted_at TEXT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending',
    FOREIGN KEY (employee_id) REFERENCES employees(id)
  )`,
  `CREATE TABLE IF NOT EXISTS timeclock_sessions (
    id TEXT PRIMARY KEY,
    employee_id TEXT NOT NULL,
    status TEXT NOT NULL,
    clocked_in_at TEXT NULL,
    break_started_at TEXT NULL,
    clocked_out_at TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (employee_id) REFERENCES employees(id)
  )`,
  `CREATE TABLE IF NOT EXISTS backup_history (
    id TEXT PRIMARY KEY,
    backup_type TEXT NOT NULL,
    file_path TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_size_bytes INTEGER NULL,
    database_size_bytes INTEGER NULL,
    status TEXT NOT NULL,
    error_message TEXT NULL,
    created_at TEXT NOT NULL,
    restored_at TEXT NULL,
    restored_by_employee_id TEXT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS local_errors (
    id TEXT PRIMARY KEY,
    source TEXT NOT NULL,
    message TEXT NOT NULL,
    stack TEXT NULL,
    context_json TEXT NULL,
    created_at TEXT NOT NULL,
    resolved_at TEXT NULL
  )`,
  "CREATE INDEX IF NOT EXISTS idx_customers_name ON customers(last_name, first_name)",
  "CREATE INDEX IF NOT EXISTS idx_customers_first_name ON customers(first_name)",
  "CREATE INDEX IF NOT EXISTS idx_customers_last_name ON customers(last_name)",
  "CREATE INDEX IF NOT EXISTS idx_customers_phone ON customers(phone)",
  "CREATE INDEX IF NOT EXISTS idx_customers_email ON customers(email)",
  "CREATE INDEX IF NOT EXISTS idx_vehicles_customer_id ON vehicles(customer_id)",
  "CREATE INDEX IF NOT EXISTS idx_vehicles_vin ON vehicles(vin)",
  "CREATE INDEX IF NOT EXISTS idx_vehicles_plate_number ON vehicles(plate)",
  "CREATE INDEX IF NOT EXISTS idx_vehicles_plate_state ON vehicles(plate_state)",
  "CREATE INDEX IF NOT EXISTS idx_vehicles_plate ON vehicles(plate, plate_state)",
  "CREATE INDEX IF NOT EXISTS idx_vehicles_year_make_model ON vehicles(year, make, model)",
  "CREATE INDEX IF NOT EXISTS idx_tickets_status ON tickets(status)",
  "CREATE INDEX IF NOT EXISTS idx_tickets_invoice_number ON tickets(invoice_number)",
  "CREATE INDEX IF NOT EXISTS idx_tickets_external_id ON tickets(external_id)",
  "CREATE INDEX IF NOT EXISTS idx_tickets_bay ON tickets(bay)",
  "CREATE INDEX IF NOT EXISTS idx_service_history_vehicle ON service_history(vehicle_id)",
  "CREATE INDEX IF NOT EXISTS idx_service_history_customer ON service_history(customer_id)",
  "CREATE INDEX IF NOT EXISTS idx_service_packages_active ON service_packages(active, sort_order)",
  "CREATE INDEX IF NOT EXISTS idx_service_packages_external ON service_packages(external_source, external_id)",
  "CREATE INDEX IF NOT EXISTS idx_catalog_items_active ON service_catalog_items(active, category)",
  "CREATE INDEX IF NOT EXISTS idx_ticket_package_details_ticket ON ticket_package_details(ticket_id)",
  "CREATE INDEX IF NOT EXISTS idx_window_stickers_ticket ON window_stickers(ticket_id)",
  "CREATE INDEX IF NOT EXISTS idx_print_jobs_ticket ON print_jobs(ticket_id, created_at)",
  "CREATE INDEX IF NOT EXISTS idx_print_jobs_document_type ON print_jobs(document_type, status)",
  "CREATE INDEX IF NOT EXISTS idx_vin_decode_cache_vin ON vin_decode_cache(vin)",
  "CREATE INDEX IF NOT EXISTS idx_fuel_economy_cache_key ON fuel_economy_cache(cache_key)",
  "CREATE INDEX IF NOT EXISTS idx_geocoding_cache_key ON geocoding_cache(cache_key)",
  "CREATE INDEX IF NOT EXISTS idx_vehicle_info_lookup_vehicle ON vehicle_info_lookup_history(vehicle_id, created_at)",
  "CREATE INDEX IF NOT EXISTS idx_vehicle_info_lookup_provider ON vehicle_info_lookup_history(provider, created_at)",
  "CREATE INDEX IF NOT EXISTS idx_vehicle_info_search_query ON vehicle_info_search_cache(query, provider)",
  "CREATE INDEX IF NOT EXISTS idx_vehicle_catalog_cache_key ON vehicle_catalog_cache(cache_key)",
  "CREATE INDEX IF NOT EXISTS idx_vehicle_catalog_options_year ON vehicle_catalog_options(year)",
  "CREATE INDEX IF NOT EXISTS idx_vehicle_catalog_options_year_make ON vehicle_catalog_options(year, make)",
  "CREATE INDEX IF NOT EXISTS idx_vehicle_catalog_options_ymm ON vehicle_catalog_options(year, make, model)",
  "CREATE INDEX IF NOT EXISTS idx_vehicle_catalog_options_provider_id ON vehicle_catalog_options(provider_option_id)",
  "CREATE INDEX IF NOT EXISTS idx_quotes_quote_number ON quotes(quote_number)",
  "CREATE INDEX IF NOT EXISTS idx_quotes_status ON quotes(status)",
  "CREATE INDEX IF NOT EXISTS idx_quote_items_quote_id ON quote_items(quote_id)",
  "CREATE INDEX IF NOT EXISTS idx_loyalty_sync_queue_status ON loyalty_sync_queue(status)",
  "CREATE INDEX IF NOT EXISTS idx_loyalty_sync_queue_event ON loyalty_sync_queue(event_type)",
  "CREATE INDEX IF NOT EXISTS idx_loyalty_sync_queue_entity ON loyalty_sync_queue(entity_id)",
  "CREATE INDEX IF NOT EXISTS idx_loyalty_sync_queue_created ON loyalty_sync_queue(created_at)",
  "CREATE INDEX IF NOT EXISTS idx_vehicle_punch_cards_vehicle ON vehicle_punch_cards(vehicle_id)",
  "CREATE INDEX IF NOT EXISTS idx_vehicle_punch_events_card ON vehicle_punch_events(punch_card_id)",
  "CREATE INDEX IF NOT EXISTS idx_referral_rewards_referred ON referral_rewards(referred_customer_id, status)",
  "CREATE INDEX IF NOT EXISTS idx_customer_coupons_customer ON customer_coupons(customer_id, status)",
  "CREATE INDEX IF NOT EXISTS idx_ticket_coupon_applications_ticket ON ticket_coupon_applications(ticket_id, status)",
  "CREATE INDEX IF NOT EXISTS idx_ticket_coupon_applications_coupon ON ticket_coupon_applications(coupon_id, status)",
  "CREATE INDEX IF NOT EXISTS idx_employees_active ON employees(active, role)",
  "CREATE INDEX IF NOT EXISTS idx_audit_log_created ON audit_log(created_at)",
  "CREATE INDEX IF NOT EXISTS idx_audit_log_entity ON audit_log(entity_type, entity_id)",
  "CREATE INDEX IF NOT EXISTS idx_audit_log_actor ON audit_log(actor_employee_id)",
  "CREATE UNIQUE INDEX IF NOT EXISTS idx_daily_closeouts_date ON daily_closeouts(business_date)",
  "CREATE INDEX IF NOT EXISTS idx_employee_time_entries_employee ON employee_time_entries(employee_id, timestamp)",
  "CREATE INDEX IF NOT EXISTS idx_employee_time_entries_type ON employee_time_entries(entry_type, timestamp)",
  "CREATE INDEX IF NOT EXISTS idx_timeclock_sessions_employee ON timeclock_sessions(employee_id, status)",
  "CREATE INDEX IF NOT EXISTS idx_backup_history_created ON backup_history(created_at)",
  "CREATE INDEX IF NOT EXISTS idx_backup_history_status ON backup_history(status)",
  "CREATE INDEX IF NOT EXISTS idx_local_errors_created ON local_errors(created_at)",
  "CREATE INDEX IF NOT EXISTS idx_local_errors_resolved ON local_errors(resolved_at)",
  "CREATE INDEX IF NOT EXISTS idx_tickets_external ON tickets(external_source, external_id)",
  "CREATE INDEX IF NOT EXISTS idx_customers_external ON customers(external_source, external_id)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_external ON inventory_items(external_source, external_id)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_sku ON inventory_items(sku)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_product_id ON inventory_items(product_id)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_barcode ON inventory_items(barcode)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_name ON inventory_items(name)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_product_type ON inventory_items(product_type)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_inventory_type ON inventory_items(inventory_type)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_vendor ON inventory_items(vendor)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_brand ON inventory_items(brand)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_supplier ON inventory_items(supplier)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_viscosity ON inventory_items(viscosity)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_active ON inventory_items(active)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_movements_item ON inventory_movements(inventory_item_id, created_at)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_count_sheets_status ON inventory_count_sheets(status)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_count_sheet_items_sheet ON inventory_count_sheet_items(count_sheet_id)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_count_sheet_items_item ON inventory_count_sheet_items(inventory_item_id)",
  "CREATE INDEX IF NOT EXISTS idx_suppliers_name ON suppliers(name)",
  "CREATE INDEX IF NOT EXISTS idx_purchase_orders_status ON purchase_orders(status)",
  "CREATE INDEX IF NOT EXISTS idx_purchase_order_items_order ON purchase_order_items(purchase_order_id)",
  "CREATE INDEX IF NOT EXISTS idx_purchase_order_items_item ON purchase_order_items(inventory_item_id)",
  "CREATE INDEX IF NOT EXISTS idx_import_errors_batch ON import_errors(batch_id)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_low_stock ON inventory_items(quantity_on_hand, reorder_point)",
  "CREATE INDEX IF NOT EXISTS idx_sync_queue_status ON sync_queue(status)"
];

export interface ColumnMigration {
  tableName: string;
  columnName: string;
  columnDefinition: string;
}

export const columnMigrations: ColumnMigration[] = [
  { tableName: "tickets", columnName: "invoice_number", columnDefinition: "TEXT NULL" },
  { tableName: "tickets", columnName: "bay", columnDefinition: "TEXT NULL" },
  { tableName: "tickets", columnName: "customer_concern", columnDefinition: "TEXT NULL" },
  { tableName: "tickets", columnName: "technician_notes", columnDefinition: "TEXT NULL" },
  { tableName: "tickets", columnName: "internal_notes", columnDefinition: "TEXT NULL" },
  { tableName: "tickets", columnName: "check_in_id", columnDefinition: "TEXT NULL" },
  { tableName: "tickets", columnName: "completed_at", columnDefinition: "TEXT NULL" },
  { tableName: "tickets", columnName: "payment_status", columnDefinition: "TEXT NOT NULL DEFAULT 'unpaid'" },
  { tableName: "tickets", columnName: "applied_coupon_ids", columnDefinition: "TEXT NULL" },
  { tableName: "tickets", columnName: "free_oil_change_redeemed", columnDefinition: "INTEGER NOT NULL DEFAULT 0" },
  { tableName: "tickets", columnName: "external_source", columnDefinition: "TEXT NULL" },
  { tableName: "tickets", columnName: "external_id", columnDefinition: "TEXT NULL" },
  { tableName: "tickets", columnName: "is_imported", columnDefinition: "INTEGER NOT NULL DEFAULT 0" },
  { tableName: "tickets", columnName: "original_import_json", columnDefinition: "TEXT NULL" },
  { tableName: "tickets", columnName: "imported_at", columnDefinition: "TEXT NULL" },
  { tableName: "tickets", columnName: "started_at", columnDefinition: "TEXT NULL" },
  { tableName: "tickets", columnName: "created_by_employee_id", columnDefinition: "TEXT NULL" },
  { tableName: "tickets", columnName: "started_by_employee_id", columnDefinition: "TEXT NULL" },
  { tableName: "tickets", columnName: "completed_by_employee_id", columnDefinition: "TEXT NULL" },
  { tableName: "tickets", columnName: "canceled_by_employee_id", columnDefinition: "TEXT NULL" },

  { tableName: "customers", columnName: "external_source", columnDefinition: "TEXT NULL" },
  { tableName: "customers", columnName: "external_id", columnDefinition: "TEXT NULL" },
  { tableName: "customers", columnName: "is_imported", columnDefinition: "INTEGER NOT NULL DEFAULT 0" },
  { tableName: "customers", columnName: "app_email", columnDefinition: "TEXT NULL" },
  { tableName: "customers", columnName: "app_phone", columnDefinition: "TEXT NULL" },
  { tableName: "customers", columnName: "app_link_status", columnDefinition: "TEXT NULL" },
  { tableName: "customers", columnName: "app_linked_at", columnDefinition: "TEXT NULL" },

  { tableName: "vehicles", columnName: "external_source", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "external_id", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "is_imported", columnDefinition: "INTEGER NOT NULL DEFAULT 0" },
  { tableName: "vehicles", columnName: "sub_model", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "trim", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "series", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "body_class", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "vehicle_type", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "doors", columnDefinition: "INTEGER NULL" },
  { tableName: "vehicles", columnName: "drive_type", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "fuel_type", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "engine_cylinders", columnDefinition: "INTEGER NULL" },
  { tableName: "vehicles", columnName: "engine_displacement_l", columnDefinition: "REAL NULL" },
  { tableName: "vehicles", columnName: "engine_displacement_cc", columnDefinition: "REAL NULL" },
  { tableName: "vehicles", columnName: "engine_model", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "engine_configuration", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "manufacturer", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "plant_country", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "plant_state", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "transmission_style", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "gvwr", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "brake_system_type", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "oil_capacity", columnDefinition: "REAL NULL" },
  { tableName: "vehicles", columnName: "oil_filter_sku", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "oil_filter_inventory_item_id", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "air_filter_sku", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "cabin_filter_sku", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "vehicle_info_notes", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "vehicle_info_source_url", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "vehicle_info_source_title", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "vehicle_info_verified_at", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "vehicle_info_verified_by_employee_id", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "last_oil_change_date", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "last_oil_change_mileage", columnDefinition: "INTEGER NULL" },
  { tableName: "vehicles", columnName: "vin_decoded_at", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "vin_decode_source", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "vin_decode_confidence", columnDefinition: "TEXT NULL" },
  { tableName: "vehicles", columnName: "vin_decode_raw_json", columnDefinition: "TEXT NULL" },

  { tableName: "ticket_items", columnName: "item_type", columnDefinition: "TEXT NULL" },
  { tableName: "ticket_items", columnName: "package_id", columnDefinition: "TEXT NULL" },
  { tableName: "ticket_items", columnName: "inventory_item_id", columnDefinition: "TEXT NULL" },
  { tableName: "ticket_items", columnName: "cost", columnDefinition: "REAL NULL" },
  { tableName: "ticket_items", columnName: "sku", columnDefinition: "TEXT NULL" },
  { tableName: "ticket_items", columnName: "product_id", columnDefinition: "TEXT NULL" },
  { tableName: "ticket_items", columnName: "source_price_type", columnDefinition: "TEXT NULL" },
  { tableName: "ticket_items", columnName: "external_source", columnDefinition: "TEXT NULL" },
  { tableName: "ticket_items", columnName: "external_id", columnDefinition: "TEXT NULL" },
  { tableName: "ticket_items", columnName: "is_imported", columnDefinition: "INTEGER NOT NULL DEFAULT 0" },
  { tableName: "ticket_items", columnName: "original_import_json", columnDefinition: "TEXT NULL" },
  { tableName: "ticket_items", columnName: "inventory_decremented", columnDefinition: "INTEGER NOT NULL DEFAULT 0" },
  { tableName: "ticket_items", columnName: "added_by_employee_id", columnDefinition: "TEXT NULL" },
  { tableName: "ticket_items", columnName: "removed_by_employee_id", columnDefinition: "TEXT NULL" },

  { tableName: "payments", columnName: "paid_at", columnDefinition: "TEXT NULL" },
  { tableName: "payments", columnName: "payment_subtype", columnDefinition: "TEXT NULL" },
  { tableName: "payments", columnName: "memo", columnDefinition: "TEXT NULL" },
  { tableName: "payments", columnName: "external_source", columnDefinition: "TEXT NULL" },
  { tableName: "payments", columnName: "external_id", columnDefinition: "TEXT NULL" },
  { tableName: "payments", columnName: "is_imported", columnDefinition: "INTEGER NOT NULL DEFAULT 0" },
  { tableName: "payments", columnName: "employee_id", columnDefinition: "TEXT NULL" },

  { tableName: "service_history", columnName: "external_source", columnDefinition: "TEXT NULL" },
  { tableName: "service_history", columnName: "external_id", columnDefinition: "TEXT NULL" },
  { tableName: "service_history", columnName: "is_imported", columnDefinition: "INTEGER NOT NULL DEFAULT 0" },

  { tableName: "inventory_items", columnName: "external_source", columnDefinition: "TEXT NULL" },
  { tableName: "inventory_items", columnName: "external_id", columnDefinition: "TEXT NULL" },
  { tableName: "inventory_items", columnName: "is_imported", columnDefinition: "INTEGER NOT NULL DEFAULT 0" },
  { tableName: "inventory_items", columnName: "product_id", columnDefinition: "TEXT NULL" },
  { tableName: "inventory_items", columnName: "product_type", columnDefinition: "TEXT NULL" },
  { tableName: "inventory_items", columnName: "inventory_type", columnDefinition: "TEXT NULL" },
  { tableName: "inventory_items", columnName: "measurement", columnDefinition: "TEXT NULL" },
  { tableName: "inventory_items", columnName: "viscosity", columnDefinition: "TEXT NULL" },
  { tableName: "inventory_items", columnName: "oil_formulation", columnDefinition: "TEXT NULL" },
  { tableName: "inventory_items", columnName: "quantity_sold_last_30_days", columnDefinition: "REAL NULL" },
  { tableName: "inventory_items", columnName: "replacement_cost", columnDefinition: "REAL NULL" },
  { tableName: "inventory_items", columnName: "avg_cost", columnDefinition: "REAL NULL" },
  { tableName: "inventory_items", columnName: "min_quantity", columnDefinition: "REAL NULL" },
  { tableName: "inventory_items", columnName: "max_quantity", columnDefinition: "REAL NULL" },
  { tableName: "inventory_items", columnName: "sequence_id", columnDefinition: "TEXT NULL" },
  { tableName: "inventory_items", columnName: "original_import_json", columnDefinition: "TEXT NULL" },
  { tableName: "inventory_items", columnName: "brand", columnDefinition: "TEXT NULL" },
  { tableName: "inventory_items", columnName: "supplier", columnDefinition: "TEXT NULL" },
  { tableName: "inventory_items", columnName: "tax_exempt", columnDefinition: "INTEGER NOT NULL DEFAULT 0" },
  { tableName: "inventory_items", columnName: "trackable", columnDefinition: "INTEGER NOT NULL DEFAULT 1" },
  { tableName: "inventory_items", columnName: "sellable", columnDefinition: "INTEGER NOT NULL DEFAULT 1" },
  { tableName: "inventory_items", columnName: "replenishable", columnDefinition: "INTEGER NOT NULL DEFAULT 1" },
  { tableName: "inventory_items", columnName: "active", columnDefinition: "INTEGER NOT NULL DEFAULT 1" },
  { tableName: "inventory_movements", columnName: "employee_id", columnDefinition: "TEXT NULL" },

  { tableName: "service_packages", columnName: "visible_in_start_ticket", columnDefinition: "INTEGER NOT NULL DEFAULT 1" },
  { tableName: "service_packages", columnName: "external_source", columnDefinition: "TEXT NULL" },
  { tableName: "service_packages", columnName: "external_id", columnDefinition: "TEXT NULL" },
  { tableName: "service_packages", columnName: "internal_name", columnDefinition: "TEXT NULL" },
  { tableName: "service_packages", columnName: "package_total", columnDefinition: "REAL NULL" },
  { tableName: "service_packages", columnName: "base_service_amount", columnDefinition: "REAL NULL" },
  { tableName: "service_packages", columnName: "disposal_fee_amount", columnDefinition: "REAL NULL" },
  { tableName: "service_packages", columnName: "disposal_fee_quantity", columnDefinition: "REAL NULL" },
  { tableName: "service_packages", columnName: "mileage_interval", columnDefinition: "INTEGER NULL" },
  { tableName: "service_packages", columnName: "time_interval_months", columnDefinition: "INTEGER NULL" },
  { tableName: "service_packages", columnName: "service_1_id", columnDefinition: "TEXT NULL" },
  { tableName: "service_packages", columnName: "service_1_name", columnDefinition: "TEXT NULL" },
  { tableName: "service_packages", columnName: "service_2_id", columnDefinition: "TEXT NULL" },
  { tableName: "service_packages", columnName: "service_2_name", columnDefinition: "TEXT NULL" },
  { tableName: "service_packages", columnName: "services_json", columnDefinition: "TEXT NULL" },
  { tableName: "service_packages", columnName: "package_group_name", columnDefinition: "TEXT NULL" },

  { tableName: "ticket_package_details", columnName: "oil_filter_inventory_item_id", columnDefinition: "TEXT NULL" },
  { tableName: "ticket_package_details", columnName: "oil_filter_sku", columnDefinition: "TEXT NULL" },
  { tableName: "ticket_package_details", columnName: "oil_filter_name", columnDefinition: "TEXT NULL" },
  { tableName: "ticket_package_details", columnName: "oil_filter_source", columnDefinition: "TEXT NULL" },
  { tableName: "ticket_package_details", columnName: "oil_inventory_item_id", columnDefinition: "TEXT NULL" },
  { tableName: "ticket_package_details", columnName: "oil_sku", columnDefinition: "TEXT NULL" },
  { tableName: "ticket_package_details", columnName: "oil_name", columnDefinition: "TEXT NULL" },
  { tableName: "ticket_package_details", columnName: "oil_source", columnDefinition: "TEXT NULL" }
];

export const seedServices = [
  ["synthetic-blend-oil-change", "Synthetic Blend Oil Change", "Oil Change", 64.99, 1, 1],
  ["full-synthetic-oil-change", "Full Synthetic Oil Change", "Oil Change", 84.99, 1, 1],
  ["mobil-1-full-synthetic-oil-change", "Mobil 1 Full Synthetic Oil Change", "Oil Change", 99.99, 1, 1],
  ["diesel-oil-change", "Diesel Oil Change", "Oil Change", 119.99, 1, 1],
  ["air-filter", "Air Filter", "Filters", 24.99, 1, 0],
  ["cabin-air-filter", "Cabin Air Filter", "Filters", 34.99, 1, 0],
  ["wiper-blades", "Wiper Blades", "Wipers", 19.99, 1, 0],
  ["tire-rotation", "Tire Rotation", "Tires", 24.99, 1, 0],
  ["shop-supplies", "Shop Supplies", "Fees", 3.99, 1, 0],
  ["disposal-fee", "Disposal Fee", "Fees", 2.99, 0, 0]
] as const;

export const seedInventoryItems = [
  ["OF4622", "OF4622", "Engine Oil Filter", "Filters", "Service Champ", 3.75, 9.99, 18, 6, "Oil filter"],
  ["OF241", "OF241", "Engine Oil Filter", "Filters", "Service Champ", 3.5, 9.99, 14, 6, "Oil filter"],
  ["DURAMAX-BLND5W20", "DURAMAX-BLND5W20", "Engine Oil", "Oil", "Duramax", 18.25, 34.99, 42, 12, "Synthetic blend 5W-20"],
  ["AF1388", "AF1388", "Air Filter", "Filters", null, 8.25, 24.99, 9, 4, "Air filter"],
  ["CF10285", "CF10285", "Cabin Air Filter", "Filters", null, 10.5, 34.99, 6, 3, "Cabin air filter"]
] as const;

export const seedServicePackages = [
  ["synthetic-blend-oil-change", "Synthetic Blend Oil Change", "Oil Change", 64.99, "Duramax", "Synthetic Blend", 6, 7.99, "standard", 10.0, 1],
  ["full-synthetic-oil-change", "Full Synthetic Oil Change", "Oil Change", 79.99, "Duramax", "Full Synthetic", 6, 9.99, "standard", 10.0, 2],
  ["mobil-1-full-synthetic-oil-change", "Mobil 1 Full Synthetic Oil Change", "Oil Change", 94.99, "Mobil 1", "Full Synthetic", 5, 11.99, "standard", 10.0, 3],
  ["diesel-oil-change", "Diesel Oil Change", "Oil Change", 119.99, "Duramax", "Diesel", 10, 9.99, "standard", 15.0, 4]
] as const;

export const seedCatalogItems = [
  ["air-filter", "Air Filter", "Filters", 24.99, 0, 0, 1],
  ["premium-air-filter", "Premium Air Filter", "Filters", 34.99, 0, 0, 2],
  ["cabin-air-filter", "Cabin Air Filter", "Filters", 34.99, 0, 0, 3],
  ["premium-cabin-air-filter", "Premium Cabin Air Filter", "Filters", 44.99, 0, 0, 4],
  ["wiper-blade", "Wiper Blade", "Wipers", 19.99, 0, 0, 10],
  ["premium-wiper-blade", "Premium Wiper Blade", "Wipers", 29.99, 0, 0, 11],
  ["washer-fluid-top-off", "Washer Fluid Top-Off", "Fluids", 0.0, 0, 0, 20],
  ["coolant-top-off", "Coolant Top-Off", "Fluids", 4.99, 0, 0, 21],
  ["power-steering-fluid-top-off", "Power Steering Fluid Top-Off", "Fluids", 4.99, 0, 0, 22],
  ["brake-fluid-top-off", "Brake Fluid Top-Off", "Fluids", 4.99, 0, 0, 23],
  ["shop-supplies", "Shop Supplies", "Fees", 3.99, 1, 0, 30],
  ["disposal-fee", "Disposal Fee", "Fees", 2.99, 1, 0, 31],
  ["cartridge-filter-fee", "Cartridge Filter Fee", "Fees", 10.0, 1, 0, 32],
  ["skid-plate-fee", "Skid Plate Fee", "Fees", 5.0, 1, 0, 33],
  ["manual-discount", "Manual Discount", "Discounts", 0.0, 0, 1, 40],
  ["coupon-discount", "Coupon Discount", "Discounts", 0.0, 0, 1, 41],
  ["free-oil-change-reward", "Free Oil Change Reward", "Discounts", 0.0, 0, 1, 42],
  ["tire-rotation", "Tire Rotation", "Tires", 24.99, 0, 0, 50],
  ["battery-test", "Battery Test", "Battery", 0.0, 0, 0, 60],
  ["battery-replacement-labor", "Battery Replacement Labor", "Battery", 24.99, 0, 0, 61],
  ["light-bulb-replacement-labor", "Light Bulb Replacement Labor", "Lights", 14.99, 0, 0, 70]
] as const;
