export interface InventoryItem {
  id: string;
  sku: string | null;
  name: string;
  category: string;
  vendor: string | null;
  brand?: string | null;
  supplier?: string | null;
  cost: number;
  retail_price: number;
  quantity_on_hand: number;
  reorder_point: number;
  barcode: string | null;
  tax_exempt?: number;
  trackable?: number;
  sellable?: number;
  replenishable?: number;
  active: number;
  notes: string | null;
  product_id?: string | null;
  product_type?: string | null;
  inventory_type?: string | null;
  measurement?: string | null;
  viscosity?: string | null;
  oil_formulation?: string | null;
  quantity_sold_last_30_days?: number | null;
  replacement_cost?: number | null;
  avg_cost?: number | null;
  min_quantity?: number | null;
  max_quantity?: number | null;
  sequence_id?: string | null;
  external_source?: string | null;
  external_id?: string | null;
  is_imported?: number;
  original_import_json?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
  sync_status: string;
}
