export interface Vehicle {
  id: string;
  customer_id: string;
  vin: string | null;
  plate: string | null;
  plate_state: string | null;
  year: number | null;
  make: string | null;
  model: string | null;
  trim?: string | null;
  series?: string | null;
  body_class?: string | null;
  vehicle_type?: string | null;
  doors?: number | null;
  drive_type?: string | null;
  fuel_type?: string | null;
  engine_cylinders?: number | null;
  engine_displacement_l?: number | null;
  engine_displacement_cc?: number | null;
  engine_model?: string | null;
  engine_configuration?: string | null;
  manufacturer?: string | null;
  plant_country?: string | null;
  plant_state?: string | null;
  transmission_style?: string | null;
  gvwr?: string | null;
  brake_system_type?: string | null;
  mileage: number | null;
  oil_type: string | null;
  oil_capacity?: number | null;
  oil_filter_sku?: string | null;
  oil_filter_inventory_item_id?: string | null;
  air_filter_sku?: string | null;
  cabin_filter_sku?: string | null;
  vehicle_info_notes?: string | null;
  vehicle_info_source_url?: string | null;
  vehicle_info_source_title?: string | null;
  vehicle_info_verified_at?: string | null;
  vehicle_info_verified_by_employee_id?: string | null;
  last_oil_change_date?: string | null;
  last_oil_change_mileage?: number | null;
  vin_decoded_at?: string | null;
  vin_decode_source?: string | null;
  vin_decode_confidence?: string | null;
  vin_decode_raw_json?: string | null;
  sub_model?: string | null;
  external_source?: string | null;
  external_id?: string | null;
  is_imported?: number;
  notes: string | null;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
  sync_status: string;
}

export type VehicleInput = Omit<Vehicle, "id" | "created_at" | "updated_at" | "deleted_at" | "sync_status">;
